### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by evernat** [vertigo-io/vertigo#148]
StringIndexOutOfBoundsException pour le webservice suivant :
```java
@PathPrefix("/reference")
public class MasterdataWebServices implements WebServices {
    private final MasterdataServices masterdataServices;

    @GET("/getSim10/{id}")
    public ReferenceIdObject getSim10(@PathParam("id") final Long id) {
        return masterdataServices.getSim10(id);
    }
}
```

Stack-trace :
```java
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 21
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at io.vertigo.util.StringUtil.constToCamelCase(StringUtil.java:141)
	at io.vertigo.util.StringUtil.constToUpperCamelCase(StringUtil.java:116)
	at io.vertigo.vega.webservice.metamodel.WebServiceDefinitionBuilder.normalizePath(WebServiceDefinitionBuilder.java:111)
	at io.vertigo.vega.webservice.metamodel.WebServiceDefinitionBuilder.build(WebServiceDefinitionBuilder.java:79)
	at io.vertigo.vega.plugins.webservice.scanner.annotations.AnnotationsWebServiceScannerUtil.buildWebServiceDefinition(AnnotationsWebServiceScannerUtil.java:150)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.vertigo.vega.plugins.webservice.scanner.annotations.AnnotationsWebServiceScannerUtil.scanWebService(AnnotationsWebServiceScannerUtil.java:92)
	at io.vertigo.vega.plugins.webservice.scanner.annotations.AnnotationsWebServiceScannerPlugin.scanWebService(AnnotationsWebServiceScannerPlugin.java:35)
	at io.vertigo.vega.impl.webservice.WebServiceManagerImpl.scanComponents(WebServiceManagerImpl.java:160)
	at io.vertigo.vega.impl.webservice.WebServiceManagerImpl.provideDefinitions(WebServiceManagerImpl.java:112)
	at io.vertigo.core.definition.SimpleDefinitionProvider.get(SimpleDefinitionProvider.java:38)
	at io.vertigo.core.definition.loader.DefinitionSpaceLoader.lambda$loadDefinitionsFromComponents$4(DefinitionSpaceLoader.java:92)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.vertigo.core.definition.loader.DefinitionSpaceLoader.loadDefinitionsFromComponents(DefinitionSpaceLoader.java:95)
	at io.vertigo.app.AutoCloseableApp.<init>(AutoCloseableApp.java:105)
	... 32 more
```

**Comment by NPi2Loup** [comment]
Same issue when digits are followed by chars. fixed by 63b4c2
